name: CI/CD for SwiftyDuck

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. Check out source code
      - name: Check out code
        uses: actions/checkout@v2

      # 2. Set up Node (for future use)
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      # 3. Install dependencies (will be fast now since we have no dependencies)
      - name: Install dependencies
        run: npm install

      # 4. Build step
      - name: Build
        run: npm run build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist 